/* This code was generated by Kalix tooling.
 * As long as this file exists it will not be re-generated.
 * You are free to make changes to this file.
 */
package com.example.domain

import com.example.ChangeCounterCmd
import com.google.protobuf.empty.Empty
import org.scalatest.matchers.should.Matchers
import org.scalatest.wordspec.AnyWordSpec

class CounterSpec extends AnyWordSpec with Matchers {

  "Counter" must {

    "handle command Increase" in {
      val testKit = CounterTestKit(new Counter(_))

      val result1 = testKit.increase(ChangeCounterCmd(value = 1))
      result1.reply shouldBe Empty.defaultInstance

      // one more time
      val result2 = testKit.increase(ChangeCounterCmd(value = 1))
      result2.reply shouldBe Empty.defaultInstance
      testKit.currentState().value shouldBe 2
    }

    "handle command Decrease" in {
      val testKit = CounterTestKit(new Counter(_))

      val result1 = testKit.increase(ChangeCounterCmd(value = 1))
      result1.reply shouldBe Empty.defaultInstance
      testKit.currentState().value shouldBe 1

      val result2 = testKit.decrease(ChangeCounterCmd(value = 1))
      result2.reply shouldBe Empty.defaultInstance
      testKit.currentState().value shouldBe 0
    }

  }
}
